# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f45ce022e496aa39d707ea40e9df20ff6851623b0cab2ff7aaa31b7d6f8b71adb50147b7481bea4fd429b498c49398ab24bc769ccc7e190631fe93c9bbb0dd70

test:
  secret_key_base: b51e2088cf882c3003130ed1b636c6c37794d192c877c1e1e90f71a93ff2b4b6940ca64e700316fc2ac4abdb900a0fb78e95265664660b75a0a78facba86e151

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
